### ISSUE TITLE
The plugin in u'Calibre-Metadata-KnygosLt-0.0.2.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by jonaspetras** [darauble/Calibre-Metadata-KnygosLt#4]
calibre, version 3.39.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'Calibre-Metadata-KnygosLt-0.0.2.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.39.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 193, in load
  File "site-packages\calibre\customize\zipplugin.py", line 291, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\user\\Downloads\\Calibre-Metadata-KnygosLt-0.0.2.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by jonaspetras** [comment]
__init__.py is 0 size. If repackaged with correct one - works
